### ISSUE TITLE
no list input for client_keys: in conf.yml

### ISSUE THREAD

**Issue by Giuseppe1992** [Giuseppe1992/Distrinet#24]
ssh:
  pub_id: "YOUR PUBLIC ID"
  user: "root"
  client_keys: ["/Users/giuseppe/.ssh/id_rsa"]
  bastion: "Bastion host IP 'xxx.xxx.xxx.xxx'"

There is no noeed to have a list in client_keys

**Comment by dsaucez** [comment]
the list is needed, but we can be user friendly and allow lists and single values
