### ISSUE TITLE
Underscore character in switch and host names

### ISSUE THREAD

**Issue by helllb** [Giuseppe1992/Distrinet#51]
Hello,

Naming switches and hosts using the underscore character _ does not work. Distrinet does not report any error but the hosts and switches are not shown in the output of `lxc ls`. Not a critical bug but may save future users some trouble :-)

**Comment by Giuseppe1992** [comment]
yes,
I have to update the documentation.
lxc do not allow container names with an underscore.

Giuseppe

**Comment by Giuseppe1992** [comment]
Documentation Updated: [limitations](https://distrinet-emu.github.io/limitations.html)
