### ISSUE TITLE
Ansible interactive prompt and lxd init

### ISSUE THREAD

**Issue by helllb** [Giuseppe1992/Distrinet#52]
Hello,

The ansible playbook for automatic configuration of workers (Distrinet/mininet/mininet/provision/playbooks/configure-lxd-no-clustering.yml) does not halt. I guess the reason is that the interactive prompt `Size in GB of the new loop device` of `lxd init` does not require adding units (i.e. the user must answer with "15" instead of "15GB" for example).

For information, this happens on Ubuntu 18.04 with LXD 3.0.1.

**Comment by Giuseppe1992** [comment]
Hello,
did you use the ansible-playbooks (Distrinet/mininet/mininet/provision/playbooks/install-lxd.yml) to install lxd on the hosts?

Giuseppe

**Comment by helllb** [comment]
Yes. You can reproduce the error by using [R2Lab's](https://r2lab.inria.fr/index.md) fit01 and fit02 loaded with the u18.04 image.

```
root@fit01:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (btrfs, dir, lvm) [default=btrfs]: 
Create a new BTRFS pool? (yes/no) [default=yes]: 
Would you like to use an existing block device? (yes/no) [default=no]: 
Size in GB of the new loop device (1GB minimum) [default=39GB]: 15GB
Invalid input, try again.

Size in GB of the new loop device (1GB minimum) [default=39GB]: 15GB
Invalid input, try again

Size in GB of the new loop device (1GB minimum) [default=39GB]:
```

Thus when using the lxd configuration playbook it gets stuck at `TASK [lxd configuration]`. Editing "15GB" into "15" in the yml file for the playbook solves the problem.

**Comment by Giuseppe1992** [comment]
ok, I guess the problem is LXD 3.0.1, can you try with a version >= 3.0.3

Giuseppe

**Comment by dsaucez** [comment]
I confirm that I have no issues with using GB in LXD 3.0.4 on Debian 10.0.3 or LXD 3.0.3 on Ubuntu 18.04.4.

**Comment by helllb** [comment]
Indeed no issues with LXD 3.0.3.

Thanks to both for you!
